1.<br>
Durch eine Exception kann man eine Fehlermeldung durch Python verhindern, die die Nutzer verwirren könnte. Anstelle der Fehlermeldung kann man somit eine eigene Fehlermeldung schreiben.<br>
Exeption handling überprüft die Eingabe eines Benutzers auf Fehler und wird verwendet um einen möglichen Konvertierungsfehler oder Ähnliches zu erfassen.<br>
Ein try-Block ist Code, in dem möglicherweise eine exeption ausgelöst wird.<br>
Ein catch-Block ist Code, der für den Umgang mit dem Fehler verantwortlich ist.<br>
Eine unhandled exception ist eine exeption die ausgelöst, aber nie "gefangen" wird. Das kann zu einem Fehler oder dem Beenden bzw. Abstürzen des Programms führen.<br>
Throw bedeuted,das wenn eine ungewöhnliche Bedingung für den Programmablauf erkannt wurde, eine Instanz einer exeption erstellt wird. Diese wird dann zu einem Code "geworfen", der sie "fängt".<br>
2.<br>
```python
user_input_string = input("Enter a number:")
try:
    user_value = int(user_input_string)
except:
    print("Error, that wasn`t an integer.")
```
3.<br>
Ich denke: A,B,D,E,Error -> da man nicht durch 0 teilen kann
Ergebnis:A,B,D,E,NameError: name 'a' is not defined -> da die 6. Zeile ja durch die 9. ersetzt wurde
4.<br>
Ich denke: A,B,C,E,0.5
Ergebnis: A,B,C,E,0.5